### ISSUE TITLE
400 Bad Request on port forwarding

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [kubecost/rancher-helm-chart#2]
I just installed kubecost via the rancher app page:

<img width="1439" alt="Bildschirmfoto 2021-06-21 um 23 22 40" src="https://user-images.githubusercontent.com/10075/122829680-97251400-d2e7-11eb-843d-c48a0d2038f3.png">

And executed the command ```kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090```.

When I access the page, I only get a "400 Bad Request" error:

<img width="348" alt="Bildschirmfoto 2021-06-21 um 23 23 30" src="https://user-images.githubusercontent.com/10075/122829769-b58b0f80-d2e7-11eb-980c-9fe94da3b6a3.png">

Since we have prometheus, grafana and alert manager already installed, we disabled the checkboxes during rancher app installation.

Any ideas what is wrong?

**Comment by AjayTripathy** [comment]
Hi @h0jeZvgoxFepBQ2C sorry for the late response. What's the state of the pods in the namespace kubecost has been installed in?

What happens if you follow our default installation instructions instead of doing this through rancher? https://www.kubecost.com/install.html#show-instructions

For followups and faster responses, do you mind reaching out to support@kubecost.com ?

**Comment by dwbrown2** [comment]
We've gotten recent reports that Rancher catalog is installing an older version of Kubecost. We've investigating now.

Latest is v1.82. It may be helpful to check this on your helm deployment.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah I also saw that.

You can't also set the url to an existing prometheus server, in case you dont want to install a second prometheus server?

**Comment by h0jeZvgoxFepBQ2C** [comment]
The funny thing is, that this 400 Bad Request error comes only in firefox, but in safari it works?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Also happens with the latest helm installation (not over rancher)

**Comment by dwbrown2** [comment]
Here are the steps for using an existing Prometheus -- https://github.com/kubecost/docs/blob/master/custom-prom.md

Let us know if we can share more on this or if you're hitting a specific issue. 

Hm, very strange about Firefox.. all other browsers seem to work? @AjayTripathy can you help investigate? I can't repro on my end right now.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Chrome and Safari work fine, just Firefox shows this NGINX error somehow.. strange :D

**Comment by dwbrown2** [comment]
@h0jeZvgoxFepBQ2C I haven't been able to recreate in FF so far. Let me know if you're able to find a repro case and we'll dig in further. No worries if this is no longer a priority.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm ok, then it seems its only on my end somehow. Works for now for me in Safari, so I close this issue if it works for you in FF.
